[2024-07-24T01:50:20.200+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T01:50:20.218+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_script_dag.run_dbt manual__2024-07-24T01:50:12.535573+00:00 [queued]>
[2024-07-24T01:50:20.225+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_script_dag.run_dbt manual__2024-07-24T01:50:12.535573+00:00 [queued]>
[2024-07-24T01:50:20.225+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T01:50:20.234+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_dbt> on 2024-07-24 01:50:12.535573+00:00
[2024-07-24T01:50:20.241+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T01:50:20.242+0000] {standard_task_runner.py:64} INFO - Started process 79 to run task
[2024-07-24T01:50:20.242+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_script_dag', 'run_dbt', 'manual__2024-07-24T01:50:12.535573+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpb3hv5jes']
[2024-07-24T01:50:20.244+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask run_dbt
[2024-07-24T01:50:20.280+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_script_dag.run_dbt manual__2024-07-24T01:50:12.535573+00:00 [running]> on host 95376c4fb2d6
[2024-07-24T01:50:20.350+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_script_dag' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T01:50:12.535573+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T01:50:12.535573+00:00'
[2024-07-24T01:50:20.353+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T01:50:20.375+0000] {docker.py:367} INFO - Starting docker container from image ghcr.io/dbt-labs/dbt-postgres:1.8.2
[2024-07-24T01:50:20.384+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-07-24T01:50:21.669+0000] {docker.py:438} INFO - [0m01:50:21  Running with dbt=1.8.3
[2024-07-24T01:50:21.818+0000] {docker.py:438} INFO - [0m01:50:21  Registered adapter: postgres=1.8.2
[2024-07-24T01:50:22.111+0000] {docker.py:438} INFO - [0m01:50:22  Found 4 models, 3 data tests, 415 macros
[2024-07-24T01:50:22.114+0000] {docker.py:438} INFO - [0m01:50:22
[2024-07-24T01:50:22.254+0000] {docker.py:438} INFO - [0m01:50:22  Concurrency: 1 threads (target='dev')
[2024-07-24T01:50:22.255+0000] {docker.py:438} INFO - [0m01:50:22
[2024-07-24T01:50:22.265+0000] {docker.py:438} INFO - [0m01:50:22  1 of 4 START sql view model public.source_stop_words ........................... [RUN]
[2024-07-24T01:50:22.392+0000] {docker.py:438} INFO - [0m01:50:22  1 of 4 OK created sql view model public.source_stop_words ...................... [[32mCREATE VIEW[0m in 0.12s]
[2024-07-24T01:50:22.395+0000] {docker.py:438} INFO - [0m01:50:22  2 of 4 START sql view model public.source_videos ............................... [RUN]
[2024-07-24T01:50:22.471+0000] {docker.py:438} INFO - [0m01:50:22  2 of 4 OK created sql view model public.source_videos .......................... [[32mCREATE VIEW[0m in 0.07s]
[2024-07-24T01:50:22.476+0000] {docker.py:438} INFO - [0m01:50:22  3 of 4 START sql view model public.trending_video_counts_per_channel ........... [RUN]
[2024-07-24T01:50:22.546+0000] {docker.py:438} INFO - [0m01:50:22  3 of 4 OK created sql view model public.trending_video_counts_per_channel ...... [[32mCREATE VIEW[0m in 0.07s]
[2024-07-24T01:50:22.550+0000] {docker.py:438} INFO - [0m01:50:22  4 of 4 START sql view model public.word_counts_title ........................... [RUN]
[2024-07-24T01:50:22.618+0000] {docker.py:438} INFO - [0m01:50:22  4 of 4 OK created sql view model public.word_counts_title ...................... [[32mCREATE VIEW[0m in 0.07s]
[2024-07-24T01:50:22.644+0000] {docker.py:438} INFO - [0m01:50:22
[2024-07-24T01:50:22.644+0000] {docker.py:438} INFO - [0m01:50:22  Finished running 4 view models in 0 hours 0 minutes and 0.53 seconds (0.53s).
[2024-07-24T01:50:22.687+0000] {docker.py:438} INFO - [0m01:50:22
[2024-07-24T01:50:22.688+0000] {docker.py:438} INFO - [0m01:50:22  [32mCompleted successfully[0m
[2024-07-24T01:50:22.690+0000] {docker.py:438} INFO - [0m01:50:22
[2024-07-24T01:50:22.691+0000] {docker.py:438} INFO - [0m01:50:22  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 TOTAL=4
[2024-07-24T01:50:23.670+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T01:50:23.690+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_script_dag, task_id=run_dbt, run_id=manual__2024-07-24T01:50:12.535573+00:00, execution_date=20240724T015012, start_date=20240724T015020, end_date=20240724T015023
[2024-07-24T01:50:23.748+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T01:50:23.762+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T01:50:23.764+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
